// Header file for the ColorMatch application
// This file is generated by the ColorMatch Application in Learn Mode

// Calibration data
sensorData sdBlack = { 5300, 4470, 5730 };
sensorData sdWhite = { 34240, 29310, 39240 };

// Color Table for matching
typedef struct
{
  char    name[9];  // color name 8+nul
  colorData rgb;    // RGB value
} colorTable;

colorTable ct[] = 
{
  {"WHITE", {252, 251, 251} },
  {"BLACK", {0, 0, 0} },
  {"YELLOW", {239, 180, 76} },
  {"ORANGE", {255, 54, 54} },
  {"RED", {51, 10, 11} },
  {"GREEN", {56, 102, 64} },
  {"BLUE", {34, 59, 95} },
  {"BROWN", {140, 93, 65} },
};